version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - db
      - kafka
    environment:
      - ENCRYPTION_KEY=default_encryption_key

  executor:
    build: ./executor
    depends_on:
      - server
      - db
      - kafka
    environment:
      - ENCRYPTION_KEY=default_encryption_key

  observer:
    build: ./observer
    ports:
      - "4000:4000"
    depends_on:
      - kafka
    environment:
      - PORT=4000

  frontend:
    build: ./my-book-storage-app
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - REACT_APP_ENCRYPTION_KEY=default_encryption_key

volumes:
  db-data:
