version: "3.8"

services:
  db:
    image: bitnami/postgresql:13
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: booksdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/bitnami/postgresql/data

  kafka:
    image: bitnami/kafka:3
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:3
    ports:
      - "2181:2181"

  app:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/booksdb
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: add-book-requests
    ports:
      - "3001:3001"
    depends_on:
      - db
      - kafka

volumes:
  postgres-data:
